categories and sort-by functionality added
tashkenna/fe-nc-news pull request #7
Opened 2023-07-19 11:03 UTC by tashkenna

2023-07-19 11:18 UTC, yalicee requested changes
Your code should have function to fetch topics from api in order to filter articles instead you are filtering articles state which could lead to stale data. 

Please reuse previously implemented get all articles function to filter by topic (using axios params).

Have a think about what you need to do for sorting as well.

2023-07-20 12:49 UTC, robert112233 reviewed
It looks like you are still not making use of the backends ability to filter and sort. For example:

api/articles?topic=coding

2023-07-20 12:49 UTC, robert112233 commented on src/components/Utils/sortArticles.js
> +  };
You shouldn't need to use this logic as it already exists on the backend!

2023-07-20 14:24 UTC, MKD01 approved these changes
Great work, im happy for you to merge this in 👍

2023-07-20 14:28 UTC, merged